const translations = {
  en: {
    "hero-greeting": "Hi, I’m Victor 👋",
    "hero-role": "Creative Developer & Violinist",
    "hero-btn": "See My Work",
    "about-title": "About Me",
    "about-desc": "I'm a passionate creative who blends music and technology. I build websites, play violin, and explore AI tools.",
    "skills-title": "Skills",
    "projects-title": "Projects",
    "project1-title": "🧮 Victor 1208-2 Calculator",
    "project1-desc": "A replica of a real printing calculator with working logic using HTML, CSS, and JavaScript.",
    "project2-title": "🎨 Canva Landing Page",
    "project2-desc": "A digital product landing page built with Canva and responsive layout techniques.",
    "contact-title": "Contact Me",
    "form-name": "Your Name",
    "form-email": "Your Email",
    "form-message": "Your Message",
    "form-btn": "Send",
    "footer-text": "Made with 💻🎻 by Victor | @TekLune",
  },

  fr: {
    "hero-greeting": "Salut, je suis Victor 👋",
    "hero-role": "Développeur Créatif & Violoniste",
    "hero-btn": "Voir mon travail",
    "about-title": "À propos de moi",
    "about-desc": "Je suis un créatif passionné qui mêle musique et technologie. Je crée des sites web, je joue du violon et j'explore les outils d'IA.",
    "skills-title": "Compétences",
    "projects-title": "Projets",
    "project1-title": "🧮 Victor 1208-2 Calculatrice",
    "project1-desc": "Une réplique d'une véritable calculatrice avec logique fonctionnelle en HTML, CSS et JavaScript.",
    "project2-title": "🎨 Page Canva",
    "project2-desc": "Page de produit numérique conçue avec Canva et des techniques de mise en page responsive.",
    "contact-title": "Contactez-moi",
    "form-name": "Votre nom",
    "form-email": "Votre e-mail",
    "form-message": "Votre message",
    "form-btn": "Envoyer",
    "footer-text": "Fait avec 💻🎻 par Victor | @TekLune",
  },
  ru: {
  "hero-greeting": "Привет, я Виктор 👋",
  "hero-role": "Креативный разработчик и скрипач",
  "hero-btn": "Посмотреть работы",
  "about-title": "Обо мне",
  "about-desc": "Я творческий человек, объединяющий музыку и технологии. Создаю сайты, играю на скрипке и изучаю ИИ-инструменты.",
  "skills-title": "Навыки",
  "projects-title": "Проекты",
  "project1-title": "🧮 Victor 1208-2 Калькулятор",
  "project1-desc": "Копия настоящего калькулятора с логикой, реализованной на HTML, CSS и JavaScript.",
  "project2-title": "🎨 Лендинг Canva",
  "project2-desc": "Лендинг цифрового продукта, созданный с помощью Canva и адаптивной вёрстки.",
  "contact-title": "Связаться со мной",
  "form-name": "Ваше имя",
  "form-email": "Ваш email",
  "form-message": "Ваше сообщение",
  "form-btn": "Отправить",
  "footer-text": "Сделано с 💻🎻 Виктором | @TekLune"
},
zh: {
  "hero-greeting": "嗨，我是Victor 👋",
  "hero-role": "创意开发者和小提琴家",
  "hero-btn": "查看我的作品",
  "about-title": "关于我",
  "about-desc": "我是一位将音乐与科技融合的创意者。我制作网站，拉小提琴，并探索AI工具。",
  "skills-title": "技能",
  "projects-title": "项目",
  "project1-title": "🧮 Victor 1208-2 计算器",
  "project1-desc": "使用 HTML、CSS 和 JavaScript 重建的真实打印计算器副本。",
  "project2-title": "🎨 Canva 着陆页",
  "project2-desc": "使用 Canva 和响应式布局技术构建的数字产品着陆页。",
  "contact-title": "联系我",
  "form-name": "你的名字",
  "form-email": "你的邮箱",
  "form-message": "你的信息",
  "form-btn": "发送",
  "footer-text": "由 Victor 制作 💻🎻 | @TekLune"
},
hi: {
  "hero-greeting": "नमस्ते, मैं विक्टर हूँ 👋",
  "hero-role": "क्रिएटिव डेवलपर और वायलिन वादक",
  "hero-btn": "मेरा काम देखें",
  "about-title": "मेरे बारे में",
  "about-desc": "मैं एक ऐसा रचनात्मक व्यक्ति हूँ जो संगीत और तकनीक को मिलाता है। मैं वेबसाइट बनाता हूँ, वायलिन बजाता हूँ और AI टूल्स का अन्वेषण करता हूँ।",
  "skills-title": "कौशल",
  "projects-title": "प्रोजेक्ट्स",
  "project1-title": "🧮 Victor 1208-2 कैलकुलेटर",
  "project1-desc": "HTML, CSS और JavaScript के साथ बनाए गए एक असली प्रिंटिंग कैलकुलेटर की प्रतिकृति।",
  "project2-title": "🎨 Canva लैंडिंग पेज",
  "project2-desc": "Canva और रेस्पॉन्सिव लेआउट तकनीकों के साथ बनाया गया डिजिटल उत्पाद लैंडिंग पेज।",
  "contact-title": "मुझसे संपर्क करें",
  "form-name": "आपका नाम",
  "form-email": "आपका ईमेल",
  "form-message": "आपका संदेश",
  "form-btn": "भेजें",
  "footer-text": "Victor द्वारा बनाया गया 💻🎻 | @TekLune"
}
};
document.getElementById("language-select").addEventListener("change", function () {
  const lang = this.value;
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.getAttribute("data-i18n");
    el.textContent = translations[lang][key];
  });
});